const simpleDetails = [
  `Pulls both the Web and Test repositories onto the Jenkins agent host:
   1. Generate PAT from GitHub...
   2. Add webhook...
   3. Set up GitHub credentials in Jenkins...
   ...`,
  "Launches the Web application locally on the Jenkins environment.",
  "Executes regression tests from the Test repository against the deployed Web application.",
  "Sends the regression test report back to the developer.",
  "If all tests pass, Jenkins deploys the new version to the production web hosting environment.",
  `*** General setting-up for Jenkins Controller/Agent
   1. install Java21...
   2. install Jenkins...
   3. install MySQL...
   4. set up SMTP...
   ...`
];
export default simpleDetails;